#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Clear config cache
php artisan config:clear

# Run PHPUnit
php artisan test

# Run seeders again
php artisan migrate:fresh --seed

# Set the config:cache
php artisan config:cache
