name: Backend CI

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  laravel:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.x

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run PHPUnit
        run: php vendor/bin/phpunit

      - name: Run PHP-CS-Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --diff
